#
# .swiftlint.yml
#

# 無効ルール
disabled_rules:
  - trailing_whitespace
  - operator_whitespace

# Lint対象外ファイル
excluded:
  - Carthage
  - Pods
  - vendor
  - R.generated.swift
line_length: 300

# 変数名が２文字以上なら許可に変更
identifier_name:
  min_length: 1

