//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 1 files.
  struct file {
    /// Resource file `Secrets.plist`.
    static let secretsPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "Secrets", pathExtension: "plist")
    
    /// `bundle.url(forResource: "Secrets", withExtension: "plist")`
    static func secretsPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.secretsPlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 0 images.
  struct image {
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 4 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `ArticleDetailBodyCell`.
    static let articleDetailBodyCell: Rswift.ReuseIdentifier<ArticleDetailBodyCell> = Rswift.ReuseIdentifier(identifier: "ArticleDetailBodyCell")
    /// Reuse identifier `ArticleDetailTopInfoCell`.
    static let articleDetailTopInfoCell: Rswift.ReuseIdentifier<ArticleDetailTopInfoCell> = Rswift.ReuseIdentifier(identifier: "ArticleDetailTopInfoCell")
    /// Reuse identifier `UserArticleDetailTopInfoCell`.
    static let userArticleDetailTopInfoCell: Rswift.ReuseIdentifier<ArticleDetailTopInfoCell> = Rswift.ReuseIdentifier(identifier: "UserArticleDetailTopInfoCell")
    /// Reuse identifier `UserArticleListCell`.
    static let userArticleListCell: Rswift.ReuseIdentifier<ArticleListCell> = Rswift.ReuseIdentifier(identifier: "UserArticleListCell")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 3 storyboards.
  struct storyboard {
    /// Storyboard `ArticleDetail`.
    static let articleDetail = _R.storyboard.articleDetail()
    /// Storyboard `UserArticleDetail`.
    static let userArticleDetail = _R.storyboard.userArticleDetail()
    /// Storyboard `UserArticleList`.
    static let userArticleList = _R.storyboard.userArticleList()
    
    /// `UIStoryboard(name: "ArticleDetail", bundle: ...)`
    static func articleDetail(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.articleDetail)
    }
    
    /// `UIStoryboard(name: "UserArticleDetail", bundle: ...)`
    static func userArticleDetail(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.userArticleDetail)
    }
    
    /// `UIStoryboard(name: "UserArticleList", bundle: ...)`
    static func userArticleList(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.userArticleList)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      // There are no resources to validate
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R {
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard {
    struct articleDetail: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = ArticleDetailViewController
      
      let bundle = R.hostingBundle
      let name = "ArticleDetail"
      
      fileprivate init() {}
    }
    
    struct userArticleDetail: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UITableViewController
      
      let bundle = R.hostingBundle
      let name = "UserArticleDetail"
      
      fileprivate init() {}
    }
    
    struct userArticleList: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UserArticleListViewController
      
      let bundle = R.hostingBundle
      let name = "UserArticleList"
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
